# Generated by Django 4.2.1 on 2023-05-30 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Composition', '0002_rename_category_name_category_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Composition.author'),
        ),
    ]
